### PR TITLE
Add "threasafe: true" to better align with the doc

### PR DESCRIPTION
**Pull request by marslangoog**
See https://cloud.google.com/appengine/docs/php/

### CODE REVIEW

**Comment by bshaffer** [comment]
LGTM

**Review by LawrenceMok — APPROVED** [review]
I think this should be approved. As the docs mention about threadsafe but the sample isn't using it

**Comment by bshaffer** [comment]
I went through [the guestbook tutorial](https://cloud.google.com/appengine/docs/standard/php/getting-started/creating-guestbook) and could not find any mention of threadsafe. What are you referring to @LawrenceMok ?

**Comment by LawrenceMok** [comment]
From here:
https://cloud.google.com/appengine/docs/standard/php/quickstart

Mentions: "This application is threadsafe so the same instance can handle several simultaneous requests. Threadsafe is an advanced feature and can result in erratic behavior if your application is not specifically designed to be threadsafe."

The view on Github button above this links to https://github.com/GoogleCloudPlatform/appengine-php-guestbook/blob/phase0-helloworld/app.yaml

**Pull request merged**
