### PR TITLE
Update helloworld.php

### PR DESCRIPTION
**Pull request by carieshmarie**
Add region tag so the Guestbook tutorial docs can point to the last branch for the entire code walkthrough.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@carieshmarie I assume you're googler. Have you looked at go/github and signed up there?

**Comment by tmatsuo** [comment]
Also the comments should be `//`, not HTML style comment

**Comment by tmatsuo** [comment]
I will do that in #16 so closing

**Comment by carieshmarie** [comment]
Thanks, Takashi! I've registered my GitHub account.

**Pull request closed without merging**
